behaviors:
  SzitakotoBehavior:
    trainer_type: ppo
    time_horizon: 32 
    max_steps: 1e7 
    hyperparameters:
      learning_rate: 8e-4
      batch_size: 2048 
      buffer_size: 50000 
      num_epoch: 3
    network_settings:
      normalize: true
      num_layers: 3 
      hidden_units: 256 
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    summary_freq: 50000
    threaded: false

torch_settings:
  device: cuda
  timeout_wait: 500
