behaviors:
  SzitakotoBehavior:
    trainer_type: ppo
    time_horizon: 256
    max_steps: 2e7
    hyperparameters:
      learning_rate: 5e-4
      batch_size: 4096
      buffer_size: 50000
      num_epoch: 5
    network_settings:
      normalize: true
      num_layers: 3
      hidden_units: 256
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    summary_freq: 50000
    threaded: true

torch_settings:
  device: cuda
  timeout_wait: 500
